version: "3.8"

services:
  ldaptive:
    build: .
    ports:
      - 9003:9003
      - 10001:10001
    volumes:
      - $HOME/.m2:/root/.m2
      - $PWD:/apps/ldaptive
    environment:
      - HOST=ldap-test
      - PORT=389
      - BASE_DN=ou=test,dc=vt,dc=edu
      - BIND_DN=uid=1,ou=test,dc=vt,dc=edu
      - BIND_CREDENTIAL=VKSxXwlU7YssGl1foLMH2mGMWkifbODb1djfJ4t2
      - PROFILE_CLASS
      - THREAD_COUNT
      - THREAD_SLEEP
      - ITERATIONS
      - USE_YOURKIT
    networks:
      ldap_net:
        ipv4_address: 172.28.1.10
    command: >
      bash -c "export DEBIAN_FRONTEND=noninteractive &&
      cd /apps/ldaptive && profile/run"

  ldap-test:
    image: dhawes/ldap-test-openldap:latest
    ports:
      - "389:389"
      - "10389:10389"
      - "636:636"
      - "10636:10636"
      - "88:88"
    networks:
      ldap_net:
        ipv4_address: 172.28.1.11
    logging:
      #driver: "json-file"
      driver: "none"
      options:
        max-size: "100M"
        max-file: "5"

  ldap-test-2:
    image: dhawes/ldap-test-openldap:latest
    ports:
      - "390:389"
      - "10390:10389"
      - "637:636"
      - "10637:10636"
      - "89:88"
    networks:
      ldap_net:
        ipv4_address: 172.28.1.12
    logging:
      #driver: "json-file"
      driver: "none"
      options:
        max-size: "100M"
        max-file: "5"

  ldap-test-3:
    image: dhawes/ldap-test-openldap:latest
    ports:
      - "391:389"
      - "10391:10389"
      - "638:636"
      - "10638:10636"
      - "90:88"
    networks:
      ldap_net:
        ipv4_address: 172.28.1.13
    logging:
      #driver: "json-file"
      driver: "none"
      options:
        max-size: "100M"
        max-file: "5"

networks:
  ldap_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

