services:
  ldaptive:
    build: .
    ports:
      - "127.0.0.1:9003:9003"
      - "127.0.0.1:10001:10001"
    volumes:
      - $HOME/.m2:/root/.m2
      - $PWD:/apps/ldaptive
    environment:
      - HOST=ldap-test
      - PORT=389
      - BASE_DN=ou=test,dc=vt,dc=edu
      - BIND_DN=uid=1,ou=test,dc=vt,dc=edu
      - BIND_CREDENTIAL=VKSxXwlU7YssGl1foLMH2mGMWkifbODb1djfJ4t2
      - PROFILE_CLASS
      - THREAD_COUNT
      - THREAD_SLEEP
      - ITERATIONS
      - USE_YOURKIT
    networks:
      ldap_net:
        ipv4_address: 172.28.1.10
    command: >
      bash -c "export DEBIAN_FRONTEND=noninteractive &&
      cd /apps/ldaptive && profile/run"

  ldap-test:
    image: dhawes/ldap-test-openldap:latest
    ports:
      - "127.0.0.1:389:389"
      - "127.0.0.1:10389:10389"
      - "127.0.0.1:636:636"
      - "127.0.0.1:10636:10636"
      - "127.0.0.1:88:88"
    networks:
      ldap_net:
        ipv4_address: 172.28.1.11
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "5"

  ldap-test-2:
    image: dhawes/ldap-test-openldap:latest
    ports:
      - "127.0.0.1:390:389"
      - "127.0.0.1:10390:10389"
      - "127.0.0.1:637:636"
      - "127.0.0.1:10637:10636"
      - "127.0.0.1:89:88"
    networks:
      ldap_net:
        ipv4_address: 172.28.1.12
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "5"

  ldap-test-3:
    image: dhawes/ldap-test-openldap:latest
    ports:
      - "127.0.0.1:391:389"
      - "127.0.0.1:10391:10389"
      - "127.0.0.1:638:636"
      - "127.0.0.1:10638:10636"
      - "127.0.0.1:90:88"
    networks:
      ldap_net:
        ipv4_address: 172.28.1.13
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "5"

networks:
  ldap_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

