services:
  ldaptive:
    build: .
    volumes:
      - $HOME/.m2:/root/.m2
      - $PWD:/apps/ldaptive
    command: >
      bash -c "export DEBIAN_FRONTEND=noninteractive &&
      cd /apps/ldaptive && fuzz/run"
